export const environment = {
  production: true,
//  LightingSystemSignlRHubUrl: 'https://localhost:5003/HomeLightSystemHub',
LightingSystemSignlRHubUrl: 'https://homeautomationsignalr20210407210041.azurewebsites.net/HomeLightSystemHub',
 //LightingSystemServiceUrl: 'https://localhost:5001/',
  LightingSystemServiceUrl: 'https://homeautomationlightingsystemapi20210403203211.azurewebsites.net/',
  // LightingSystemSignlRHubUrl: 'https://lightingsystemapi20200320102759.azurewebsites.net/HomeLightSystemHub',
  // LightingSystemServiceUrl: 'https://lightingsystemapi20200320102759.azurewebsites.net/',
  //  LightingSystemSignlRHubUrl: 'https://homeautomationlightapi.azurewebsites.net/HomeLightSystemHub',
  // LightingSystemServiceUrl: 'https://homeautomationlightapi.azurewebsites.net/',
  IdentityServerbaseUrl: 'https://homeautomationidentityservice20190519114609.azurewebsites.net/',
  // IdentityServerbaseUrl: 'https://homeautomationidentityservice20190519114609.azurewebsites.net/',
  //SoundSystemSignlRHubUrl: 'https://localhost:5003/HomeSoundSystemHub',
  SoundSystemSignlRHubUrl: 'https://homeautomationsignalr20210407210041.azurewebsites.net/HomeSoundSystemHub',
};
